version: '3.4'
services:
  rest-service:
    container_name: rest-service
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PORT = ${PORT}
    ports:
      - 4000:${PORT}
    env_file:
      - .env
    volumes:
      - ./:/nodejs2022Q2-service
      - ignore:/nodejs2022Q2-service/node_modules/
volumes:
  ignore:
